language: node_js
os: linux
dist: bionic
strategy: git
node_js:
  - 14
install:
  - npm install
cache:
  yarn: true
  directories:
    - public
    - .cache
script:
  - npm run build # Generate static HTML files

# Here is the magic part
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: build
  on:
    branch: master
