---
# https://circleci.com/docs/2.0/configuration-reference
version: 2.1

workflows:
  main:
    jobs:
      - lint
      - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - lint
            - build

jobs:

  lint:
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - run: gem install mdl
      - run: mdl --config .mdlrc .

  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - restore_cache:
          key: qAIRa-node-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm run build

      - save_cache:
          paths:
            - node_modules
            - .cache
            - public
          key: qAIRa-node-{{ checksum "package-lock.json" }}

      - persist_to_workspace:
          root: ./
          paths: build

  deploy:
    docker:
      - image: cibuilds/base:latest
    steps:
      # deploy.sh dependencies
      - run: apk add rsync

      # clone repo (required to access `.circleci/deploy.sh`)
      - run: git clone https://github.com/qAIRa/qAIRa.github.io.git

      # checkout generated html
      - attach_workspace:
          at: build

      # deploy to production
      - add_ssh_keys:
         fingerprints:
           - f4:c5:fa:bd:01:c6:02:0d:36:63:70:a2:0e:eb:cb:c1
      - deploy:
          name: Deploy to GitHub Pages
          command: ./qAIRa.github.io/.circleci/deploy.sh

workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
